### ISSUE TITLE
Standard heart emoji is black instead of red

### ISSUE THREAD

**Issue by apackin** [Kikobeats/emojis-list#18]
https://github.com/Kikobeats/emojis-list/blob/master/index.js#L2445
I believe this should be the standard (red) heart ( https://unicode.org/emoji/charts/full-emoji-list.html#2764 ) as indicated by the keyword in https://github.com/Kikobeats/emojis-keywords/blob/master/index.js#L2445

**Comment by Kikobeats** [comment]
Thanks for submitting. Actually, the list is very outdated, need to run the script and see how it changes. Can do it into a PR? 🙂

**Comment by almeidx** [comment]
@Kikobeats bit late, but I ran the update script just now. https://github.com/Kikobeats/emojis-list/pull/27
