### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).filter is not a function

### ISSUE THREAD

**Issue by p2227** [Kikobeats/emojis-list#2]
https://github.com/webpack/loader-utils/issues/36

I think there are some conflicts between `webpack` `loader-utils` `emojis-list` and `react-router-proxy-loader`

**Comment by Kikobeats** [comment]
I read your words

```
the conflict is : emojis-list exports a json file. there is no problem while it is in node environment.
but in webpack , the require function is rewrite to __webpack_require__ . it can't load json file without json-loader
```

so finally using json-loader you can load the lib? or is necessary a modification in this lib?

**Comment by p2227** [comment]
It can.
Update the docs?

**Comment by Kikobeats** [comment]
this library docs? can you make a PR please? 😄
