### ISSUE TITLE
Add new emoji 12.1

### ISSUE THREAD

**Issue by kldkv** [Kikobeats/emojis-list#21]
[Blog unicode](http://blog.unicode.org/2019/10/emoji-121-release-168-emoji-added.html)
[Unicode standard 12.1](http://www.unicode.org/Public/emoji/12.1/)

**Comment by Kikobeats** [comment]
we use https://github.com/Kikobeats/emojis-list/blob/master/update.js for updating the list, so first, the new emoji needs to be available there 🙂

right now I'm only seeing this new emoji

<img width="311" alt="Screenshot 2019-10-28 at 16 17 24" src="https://user-images.githubusercontent.com/2096101/67691203-78e60400-f99e-11e9-8297-de7ef853be3e.png">

so still we need to wait a bit!
