### ISSUE TITLE
Integrity check failed for "emojis-list"

### ISSUE THREAD

**Issue by JenniferTactill** [Kikobeats/emojis-list#30]
<img width="646" alt="Capture d’écran 2022-06-28 à 12 22 00" src="https://user-images.githubusercontent.com/62068115/176156418-63e97aa1-32d6-4d4d-9cfa-5cb88c192e68.png">

**Comment by Kikobeats** [comment]
that's a npm issue

**Comment by hdhsyyyyy** [comment]
Error: Cannot find module 'emojis-list'
