### ISSUE TITLE
Error installing emojis-list

### ISSUE THREAD

**Issue by phygineer** [Kikobeats/emojis-list#32]
Using node v23.4.0 & npm 10.9.2

Getting below error while installing emoji-list using `npm i emojis-list`

```shell
22 http cache emojis-list@https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz 0ms (cache hit)
23 silly tarball no local data for emojis-list@https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz. Extracting by manifest.
24 http fetch GET 304 https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz 118ms (cache skip)
25 warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
26 silly tar Error: TAR_BAD_ARCHIVE: Unrecognized archive format
26 silly tar     at Unpack.warn (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/warn-mixin.js:21:40)
26 silly tar     at Unpack.warn (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/unpack.js:236:18)
26 silly tar     at Unpack.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:83:14)
26 silly tar     at Unpack.emit (node:events:525:35)
26 silly tar     at [emit] (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:313:12)
26 silly tar     at [maybeEnd] (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:468:17)
26 silly tar     at [consumeChunk] (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:476:21)
26 silly tar     at Unpack.write (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:427:25)
26 silly tar     at Unpack.end (/opt/homebrew/lib/node_modules/npm/node_modules/tar/lib/parse.js:548:14)
26 silly tar     at Pipe.end (/opt/homebrew/lib/node_modules/npm/node_modules/minipass/dist/commonjs/index.js:116:23) {
26 silly tar   recoverable: false,
26 silly tar   cwd: '/Users/yogesh/Projects/a/node_modules/emojis-list',
26 silly tar   code: 'TAR_BAD_ARCHIVE',
26 silly tar   tarCode: 'TAR_BAD_ARCHIVE'
26 silly tar }

```

**Comment by phygineer** [comment]
after switching to different network it got resolved so not an issue.

**Comment by nileshzype** [comment]
Its not working for me, still getting same error

**Comment by Kikobeats** [comment]
It seems it was a temporal issuein the npm network

**Comment by nileshzype** [comment]
Thanks for the quick response, @Kikobeats. However, I have been facing this issue for the last 48 hours. On NPM, the rest of the libraries are working properly except this one.

**Comment by divitrao** [comment]
@Kikobeats  I tried changing the network, but it didn’t work. The following link is not downloading at all:

https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz

Will this issue be resolved by NPM?

**Comment by saranglakare** [comment]
I confirmed this issue from Pune, India. Could be a CDN issue. curl on `https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz` gives ZERO bytes.

Note 1: this issue comes on fresh setup or after you run `npm cache clean --force` which clears registry cache from your machine

Note 2: this issue is affecting creation of new Angular webapp. So any beginner trying to use `ng new` will face this!

This issue is also reported on NPM: https://github.com/npm/cli/issues/7986 and yarn: https://github.com/yarnpkg/yarn/issues/9118
